from __future__ import annotations

from pydantic import BaseModel, Field


class EvaluationCase(BaseModel):
    case_id: str = Field(..., description="Unique case id")
    task: str = Field(..., description="Task description")
    model_output: str = Field(..., description="Answer generated by model")
    required_keywords: list[str] = Field(default_factory=list)
    fail_patterns: list[str] = Field(default_factory=list)


class EvaluationResult(BaseModel):
    case_id: str
    score: int
    level: str
    error_types: list[str]
    evidence: list[str]
    suggestion: str


class BatchEvaluationRequest(BaseModel):
    cases: list[EvaluationCase]


class BatchEvaluationResponse(BaseModel):
    results: list[EvaluationResult]
    report: dict


class AIReview(BaseModel):
    score: int = Field(..., ge=0, le=10)
    level: str
    error_types: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)
    suggestion: str
    review_summary: str


class AIEvaluationResponse(BaseModel):
    case_id: str
    provider: str
    model: str
    rule_result: EvaluationResult
    ai_review: AIReview
